import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { shopifyClient, parseShopifyResponse } from '../lib/shopify'
import Header from '../components/Header'
import ProductList from '../components/ProductsList'


const inter = Inter({ subsets: ['latin'] })
export default function Home({products}) {
  console.log("products:", products)
  return (
    <>
      <Head>
        <title>Kazecheese</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <ProductList products={products}/>
    </>
  )
}

export const getServerSideProps = async () => {
  // Fetch all the products
  const products = await shopifyClient.product.fetchAll();


  return {
   props: {
    products: parseShopifyResponse(products),
  },
 };
};